#!/usr/bin/env python
# -*- coding: UTF-8 -*-

from pathlib import Path
import sys


# FIXME
# Root path is not necessary, only here because import from local not site-packages
root_path = Path(__file__).parents[1]
if root_path.as_posix() not in sys.path:
    sys.path.insert(0, root_path.as_posix())

# from mypythontools import githooks, deploy

# githooks.run_tests()

# githooks.sphinx_docs_regenerate('mypythontools')
# githooks.generate_readme_from_init('mypythontools')


# deploy.deploy_to_pypi()
